/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7rCLqg3NqPS
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Spreadsheet from "react-spreadsheet";

export function MainPage( { data }) {

  return (
    <div className="bg-[#f8f8f8] min-h-screen">
      <div className="bg-[#e0e0e0] p-4 text-right">
        <span className="text-lg font-semibold">VAR: #,###.## USD</span>
        <span className="ml-4 text-lg font-semibold">ES: #,###.## USD</span>
      </div>
      <div className="flex">
        <div className="flex flex-col w-3/4 p-4">
          <Tabs className="mb-4" defaultValue="sheet1">
            <TabsList className="flex space-x-2">
              <TabsTrigger value="sheet1">Sheet 1</TabsTrigger>
              <TabsTrigger value="detail1">Detail 1</TabsTrigger>
              <TabsTrigger value="name">Name</TabsTrigger>
              <TabsTrigger value="sheet2">Sheet 2</TabsTrigger>
              <TabsTrigger value="sheet3">Sheet 3</TabsTrigger>
              <TabsTrigger value="sheet4">Sheet 4</TabsTrigger>
            </TabsList>
            <TabsContent value="sheet1">


                <div className="overflow-scroll w-30 h-screen">
                  <Spreadsheet data={data}></Spreadsheet>
                </div>
            </TabsContent>
            <TabsContent value="detail1">
              <div className="bg-white border-t border-l grid grid-cols-9">
                <div className="border-r p-2">
                  <p className="font-semibold">Detail 1</p>
                  <p>Pod 02</p>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="name">
              <div className="bg-white border-t border-l grid grid-cols-9">
                <div className="border-r p-2">
                  <p className="font-semibold">Name</p>
                  <p>Pod 03</p>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="sheet2">
              <div className="bg-white border-t border-l grid grid-cols-9">
                <div className="border-r p-2">
                  <p className="font-semibold">Sheet 2</p>
                  <p>Pod 04</p>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </div>
        <div className="w-1/4 bg-[#d0d0d0] p-4">
          <div className="flex justify-between items-center mb-4">
            <div className="w-1/3 h-2 bg-[#a0a0a0]" />
            <div className="w-1/12 h-2 bg-[#a0a0a0]" />
            <div className="w-1/6 h-2 bg-[#a0a0a0]" />
          </div>
          <div className="mb-4">
            <div className="text-lg font-semibold mb-2">Search</div>
            <Input placeholder="Search" />
          </div>
          <div className="mb-4">
            <div className="text-lg font-semibold mb-2">Tables</div>
            <Checkbox id="desk" />
            <label className="text-sm" htmlFor="desk">
              Desk
            </label>
            <br />
            <Checkbox id="pod" />
            <label className="text-sm" htmlFor="pod">
              Pod
            </label>
            <br />
            <Checkbox id="trader" />
            <label className="text-sm" htmlFor="trader">
              Trader
            </label>
            <br />
            <Checkbox id="type" />
            <label className="text-sm" htmlFor="type">
              Type
            </label>
            <br />
            <Checkbox id="pnl" />
            <label className="text-sm" htmlFor="pnl">
              PnL
            </label>
          </div>
          <div className="mb-4">
            <div className="text-lg font-semibold mb-2">Filters</div>
            <div className="h-6 bg-[#a0a0a0] mb-2" />
            <div className="h-6 bg-[#a0a0a0] mb-2" />
            <div className="h-6 bg-[#a0a0a0] mb-2" />
          </div>
          <div>
            <div className="text-lg font-semibold mb-2">Rows</div>
            <div className="h-6 bg-[#a0a0a0] mb-2" />
            <div className="h-6 bg-[#a0a0a0] mb-2" />
          </div>
          <div>
            <div className="text-lg font-semibold mb-2">Columns</div>
            <div className="h-6 bg-[#a0a0a0] mb-2" />
          </div>
          <div>
            <div className="text-lg font-semibold mb-2">Values</div>
            <div className="h-6 bg-[#a0a0a0] mb-2" />
          </div>
        </div>
      </div>
    </div>
  );
}
